name: search_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  url_launcher: ^6.3.1
  go_router: ^14.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
